/**
 * @file outbox.ts
 * @description Persistent IndexedDB outbox queue for local-first Yjs updates.
 * 
 * This queue stores binary Yjs updates generated by local client edits. It is
 * fully persistent, surviving browser crashes, tab closures, and page reloads.
 * Updates are cleared only after the server acknowledges successful insertion.
 */

const DB_NAME = 'docsync-outbox-db';
const STORE_NAME = 'outbox';
const DB_VERSION = 1;

export interface OutboxEntry {
  id: string;
  documentId: string;
  update: Uint8Array;
  createdAt: number;
}

/**
 * Open or initialize the IndexedDB outbox database.
 */
function openDB(): Promise<IDBDatabase> {
  return new Promise((resolve, reject) => {
    const request = indexedDB.open(DB_NAME, DB_VERSION);

    request.onerror = () => reject(request.error);
    request.onsuccess = () => resolve(request.result);

    request.onupgradeneeded = (event) => {
      const db = request.result;
      if (!db.objectStoreNames.contains(STORE_NAME)) {
        // We use id as keyPath. We'll also index by documentId to quickly retrieve updates per document.
        const store = db.createObjectStore(STORE_NAME, { keyPath: 'id' });
        store.createIndex('documentId', 'documentId', { unique: false });
      }
    };
  });
}

/**
 * Adds a new Yjs update to the outbox queue.
 * 
 * @param documentId Unique identifier of the document.
 * @param update The raw binary update bytes.
 */
export async function addToOutbox(documentId: string, update: Uint8Array): Promise<void> {
  const db = await openDB();
  return new Promise((resolve, reject) => {
    const transaction = db.transaction(STORE_NAME, 'readwrite');
    const store = transaction.objectStore(STORE_NAME);

    // Create entry with random ID and timestamp
    const entry: OutboxEntry = {
      id: `${documentId}-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
      documentId,
      update,
      createdAt: Date.now(),
    };

    const request = store.put(entry);

    request.onsuccess = () => resolve();
    request.onerror = () => reject(request.error);
  });
}

/**
 * Retrieves all pending updates queued for a specific document, ordered by creation time.
 * 
 * @param documentId Unique identifier of the document.
 */
export async function getPendingUpdates(documentId: string): Promise<OutboxEntry[]> {
  const db = await openDB();
  return new Promise((resolve, reject) => {
    const transaction = db.transaction(STORE_NAME, 'readonly');
    const store = transaction.objectStore(STORE_NAME);
    const index = store.index('documentId');
    const request = index.getAll(IDBKeyRange.only(documentId));

    request.onsuccess = () => {
      const results = request.result as OutboxEntry[];
      // Sort chronologically to maintain edit order
      results.sort((a, b) => a.createdAt - b.createdAt);
      resolve(results);
    };

    request.onerror = () => reject(request.error);
  });
}

/**
 * Removes successfully synchronized updates from the outbox queue.
 * 
 * @param ids List of outbox entry IDs to remove.
 */
export async function removeUpdates(ids: string[]): Promise<void> {
  if (ids.length === 0) return;
  const db = await openDB();
  return new Promise((resolve, reject) => {
    const transaction = db.transaction(STORE_NAME, 'readwrite');
    const store = transaction.objectStore(STORE_NAME);

    let completed = 0;
    let failed = false;

    ids.forEach((id) => {
      const request = store.delete(id);
      request.onsuccess = () => {
        completed++;
        if (completed === ids.length && !failed) {
          resolve();
        }
      };
      request.onerror = () => {
        if (!failed) {
          failed = true;
          reject(request.error);
        }
      };
    });
  });
}
